export type {
  ViewerPresence,
  NotificationPayload,
  ChatMessage,
  TicketUpdatePayload,
  TicketCreatePayload,
  TicketAssignedPayload,
  TicketStatusChangePayload,
  TicketMessagePayload,
  TypingPayload,
  JoinSessionAck,
  LeaveSessionAck,
  HeartbeatAck,
  MarkReadAck,
  MarkAllReadAck,
  ViewersList,
  ErrorPayload,
  ServerToClientEvents,
  ClientToServerEvents,
  SocketInitOptions,
  ManagerOptions,
  SocketOptions,
} from "./types";

export {
  useSocket,
  usePresence,
  useNotifications,
  useChatSession,
} from "@ticket-app/ui/hooks/socket";
