/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as KbIndexRouteImport } from './routes/kb/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as TicketsChar91idChar93RouteImport } from './routes/tickets/[id]'
import { Route as KbSlugRouteImport } from './routes/kb/$slug'
import { Route as AdminWorkflowsBuilderRouteImport } from './routes/admin/workflows/builder'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsChar91idChar93Route = TicketsChar91idChar93RouteImport.update({
  id: '/tickets/id',
  path: '/tickets/id',
  getParentRoute: () => rootRouteImport,
} as any)
const KbSlugRoute = KbSlugRouteImport.update({
  id: '/kb/$slug',
  path: '/kb/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsBuilderRoute = AdminWorkflowsBuilderRouteImport.update({
  id: '/admin/workflows/builder',
  path: '/admin/workflows/builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/todos': typeof TodosRoute
  '/kb/$slug': typeof KbSlugRoute
  '/tickets/id': typeof TicketsChar91idChar93Route
  '/chat/': typeof ChatIndexRoute
  '/kb/': typeof KbIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/workflows/builder': typeof AdminWorkflowsBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/todos': typeof TodosRoute
  '/kb/$slug': typeof KbSlugRoute
  '/tickets/id': typeof TicketsChar91idChar93Route
  '/chat': typeof ChatIndexRoute
  '/kb': typeof KbIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/admin/workflows/builder': typeof AdminWorkflowsBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/todos': typeof TodosRoute
  '/kb/$slug': typeof KbSlugRoute
  '/tickets/id': typeof TicketsChar91idChar93Route
  '/chat/': typeof ChatIndexRoute
  '/kb/': typeof KbIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/workflows/builder': typeof AdminWorkflowsBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/todos'
    | '/kb/$slug'
    | '/tickets/id'
    | '/chat/'
    | '/kb/'
    | '/tickets/'
    | '/admin/workflows/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/todos'
    | '/kb/$slug'
    | '/tickets/id'
    | '/chat'
    | '/kb'
    | '/tickets'
    | '/admin/workflows/builder'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/todos'
    | '/kb/$slug'
    | '/tickets/id'
    | '/chat/'
    | '/kb/'
    | '/tickets/'
    | '/admin/workflows/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  TodosRoute: typeof TodosRoute
  KbSlugRoute: typeof KbSlugRoute
  TicketsChar91idChar93Route: typeof TicketsChar91idChar93Route
  ChatIndexRoute: typeof ChatIndexRoute
  KbIndexRoute: typeof KbIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  AdminWorkflowsBuilderRoute: typeof AdminWorkflowsBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/': {
      id: '/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/id': {
      id: '/tickets/id'
      path: '/tickets/id'
      fullPath: '/tickets/id'
      preLoaderRoute: typeof TicketsChar91idChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/$slug': {
      id: '/kb/$slug'
      path: '/kb/$slug'
      fullPath: '/kb/$slug'
      preLoaderRoute: typeof KbSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows/builder': {
      id: '/admin/workflows/builder'
      path: '/admin/workflows/builder'
      fullPath: '/admin/workflows/builder'
      preLoaderRoute: typeof AdminWorkflowsBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  TodosRoute: TodosRoute,
  KbSlugRoute: KbSlugRoute,
  TicketsChar91idChar93Route: TicketsChar91idChar93Route,
  ChatIndexRoute: ChatIndexRoute,
  KbIndexRoute: KbIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  AdminWorkflowsBuilderRoute: AdminWorkflowsBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
