export const QUEUE_NAMES = {
  EMAIL: "email",
  EMAIL_SEND: "email-send",
  EMAIL_FETCH: "email-fetch",
  TICKET: "ticket",
  WORKFLOW: "workflow",
  NOTIFICATION: "notification",
  DUNNING: "billing-dunning",
  USAGE_CHECK: "billing-usage-check",
  CSAT_EXPIRATION: "csat-expiration",
  SPAM_CHECK: "spam-check",
  AUTO_ASSIGN: "ticket-auto-assign",
  SLA_ESCALATION: "sla-escalation",
  SLA_CHECK: "sla-check",
  EXCEL_EXPORT: "excel-export",
  EXCEL_IMPORT: "excel-import",
  LICENSE_VERIFICATION: "license-verification",
  CHATBOT_ESCALATION: "chatbot-escalation",
  GDPR_SLACK_CHECK: "gdpr-slack-check",
  SOCIAL_SYNC: "social-sync",
  ECOMMERCE_SYNC: "ecommerce-sync",
  AMAZON_SYNC: "amazon-sync",
  DISQUS_SYNC: "disqus-sync",
  PUSH_NOTIFICATION: "push-notification",
  CSAT_SURVEY: "csat-survey",
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];

export {
  type EmailJobData,
  type WorkflowJobData,
  type NotificationJobData,
  type DunningJobData,
  type UsageCheckJobData,
  type CsatExpirationJobData,
  type SpamCheckJobData,
  type AutoAssignJobData,
  type SlaCheckJobData,
  type ExcelExportJobData,
  type ExcelImportJobData,
  type EmailSendJobData,
  type EmailFetchJobData,
  type LicenseVerificationJobData,
  type ChatbotEscalationJobData,
  type GdprSlackCheckJobData,
  type SocialSyncJobData,
  type EcommerceSyncJobData,
  type AmazonSyncJobData,
  type DisqusSyncJobData,
  type PushNotificationJobData,
  type TicketJobData,
} from "./types";
