import "dotenv/config";
import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().default("postgresql://postgres:@localhost:5432/ticekt"),
    CORS_ORIGIN: z.string().default("http://localhost:5173"),
    NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
    REDIS_URL: z.string().default("redis://localhost:6379"),
    CACHE_DRIVER: z.enum(["redis", "memory"]).default("memory"),
    CACHE_PREFIX: z.string().default("ticket-app"),
    SMTP_HOST: z.string().default("smtp.example.com"),
    SMTP_PORT: z.coerce.number().default(587),
    SMTP_SECURE: z.coerce.boolean().default(false),
    SMTP_USER: z.string().default(""),
    SMTP_PASS: z.string().default(""),
    SMTP_FROM: z.string().default("noreply@example.com"),
    QUEUE_PREFIX: z.string().default("ticket-app"),
    QUEUE_PROVIDER: z.enum(["bullmq", "bull", "memory"]).default("bullmq"),
    STORAGE_PROVIDER: z.enum(["s3", "minio", "local", "oracle"]).default("s3"),
    STORAGE_BUCKET: z.string().default("ticket-app-uploads"),
    STORAGE_ENDPOINT: z.string().optional(),
    STORAGE_REGION: z.string().default("us-east-1"),
    STORAGE_ACCESS_KEY: z.string().optional(),
    STORAGE_SECRET_KEY: z.string().optional(),
    STORAGE_PUBLIC_URL: z.string().optional(),
    STORAGE_LOCAL_PATH: z.string().default("./uploads"),
    STORAGE_MAX_FILE_SIZE: z.coerce.number().default(52428800),
    STORAGE_CDN_URL: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().default(""),
    STRIPE_WEBHOOK_SECRET: z.string().default(""),
    PAYTABS_SERVER_KEY: z.string().default(""),
    PAYTABS_CLIENT_KEY: z.string().default(""),
    PAYTABS_PROFILE_ID: z.string().default(""),
    PAYTABS_BASE_URL: z.url().optional(),
    GOOGLE_CLIENT_ID: z.string().default(""),
    GOOGLE_CLIENT_SECRET: z.string().default(""),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().default(""),
    FACEBOOK_CLIENT_ID: z.string().default(""),
    FACEBOOK_CLIENT_SECRET: z.string().default(""),
    APPLE_CLIENT_ID: z.string().default(""),
    TWITTER_CLIENT_ID: z.string().default(""),
    TWITTER_CLIENT_SECRET: z.string().default(""),
    WHATSAPP_PHONE_NUMBER_ID: z.string().default(""),
    WHATSAPP_WABA_ID: z.string().default(""),
    WHATSAPP_ACCESS_TOKEN: z.string().default(""),
    WHATSAPP_VERIFY_TOKEN: z.string().default(""),
    SHOPIFY_CLIENT_ID: z.string().default(""),
    SHOPIFY_CLIENT_SECRET: z.string().default(""),
    WOOCOMMERCE_CONSUMER_KEY: z.string().default(""),
    WOOCOMMERCE_CONSUMER_SECRET: z.string().default(""),
    SALLA_CLIENT_ID: z.string().default(""),
    SALLA_CLIENT_SECRET: z.string().default(""),
    ZID_CLIENT_ID: z.string().default(""),
    ZID_CLIENT_SECRET: z.string().default(""),
    WEBPUSH_VAPID_PUBLIC_KEY: z.string().default(""),
    WEBPUSH_VAPID_PRIVATE_KEY: z.string().default(""),
    APP_URL: z.string().default("http://localhost:3000"),
    APP_SECRET: z.string().default("default-secret-change-me"),
    ENCRYPTION_SECRET: z.string().default(""),
    SUBDOMAIN_SUFFIX: z.string().default("support.app"),
    DEFAULT_DOMAIN: z.string().optional(),
    LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
    LICENSE_PUBLIC_KEY_PATH: z.string().default("./keys/license-public.pem"),
    LICENSE_PUBLIC_KEY: z.string().default(""),
    LICENSE_MODE: z.enum(["cloud", "on_premise"]).default("on_premise"),
    ON_PREMISE: z.coerce.boolean().default(false),
    FACEBOOK_APP_ID: z.string().default(""),
    FACEBOOK_APP_SECRET: z.string().default(""),
    FACEBOOK_CALLBACK_URL: z
      .string()
      .default("http://localhost:3000/admin/social/facebook/callback"),
    TWITTER_CALLBACK_URL: z.string().default("http://localhost:3000/admin/social/twitter/callback"),
    GOOGLE_REDIRECT_URI: z.string().default("http://localhost:3000/oauth/google/callback"),
  },
  runtimeEnv: process.env,
  emptyStringAsUndefined: true,
});
